### ISSUE TITLE
For another editor?

### ISSUE THREAD

**Issue by Alexey-T** [colinta/SublimeFileDiffs#69]
Very good plugin.
Maybe you can write similar for CudaText? Api doc is http://wiki.freepascal.org/CudaText_API
, and dialog api is dlg_custom (needs Beta).
No diff there.

**Comment by colinta** [comment]
I hope you port this project! I don't use that editor, nor do I care to start using it. 

I ported FileDiffs - or rather, took inspiration - from TextMate when I first started using Sublime Text, and it's been fun maintaining a popular plugin. 

Since both editors use Python, and the main diffing code uses a built in Python package (difflib), it should be relatively straightforward for you to port it. But it's on you - if you want it you'll have to build it yourself.
