### ISSUE TITLE
Bug if lines of code are collapsed

### ISSUE THREAD

**Issue by rozzilla** [colinta/SublimeFileDiffs#80]
Hello.
This plugin is really useful! Thank you so much.

I found just a little bug: if you collapse a line of code in a page of Sublime and then you compare two different pages, the plugin have problems to compare the two files.

**Comment by colinta** [comment]
Thanks!  I tried to reproduce this today, the only bug I found was this: when I collapsed a line of code it was easy to also *select* that line.  When activating FileDiffs with a selection, it will automatically try to diff the selected text instead of the whole file.  This isn't really a bug, that's expected behavior.

If I just collapse the text and diff two tabs it works fine.

Can you provide more details, and maybe a screenshot?

**Comment by rozzilla** [comment]
Sorry, I've already tried this morning and I can't reproduce the issue. Probably, yesterday, between the compare of the two there was really a little bit difference (for example a break space).

**Comment by colinta** [comment]
Great!  Please close this issue whenever you think everything is working correctly.

**Comment by colinta** [comment]
Yes please do!
